name: python-3.7

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Cache VirtualEnv
      id: cache-venv
      uses: actions/cache@v1
      with:
        path: .venv
        key: ${{ runner.os }}-${{ hashFiles('*.txt') }}-python3.7

    - uses: actions/checkout@v1
      name: "Checkout Code"

    - id: bento
      name: Bento
      uses: returntocorp/bento-action@v1
      with:
        acceptTermsWithEmail: gabriel@nacaolivre.org

    - name: Run Tests
      run: make tests

    - name: "Upload coverage results to codecov.io"
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml # optional
